'use client'

import { MapPin } from 'lucide-react'

type LocationLike = {
  id: string
  name: string
  type?: string | null
  latitude?: string | number | null
  longitude?: string | number | null
  day_number?: number | null
  notes?: string | null
}

type LocationsBlockProps = {
  locations: LocationLike[]
  /**
   * Minimal fallback rendering. No SVG map here — that's art direction and
   * belongs in per-theme components (hand-sketch for Journal, topo for
   * Expedition, cream+coral route for Atelier). This block is the safety
   * net: if a theme doesn't implement its own map, we still show the points.
   */
}

/** Parse a lat/lng value into a finite number, or return null. */
function numberOrNull(v: string | number | null | undefined): number | null {
  if (v === null || v === undefined) return null
  const n = typeof v === 'number' ? v : Number(v)
  return Number.isFinite(n) ? n : null
}

/**
 * Block #5 — Locations (shared fallback).
 *
 * NOTE: this is a *new* block — it did not exist in trip-page-client.tsx
 * before TZ-5. Locations were generated by the pipeline but never rendered.
 * This component provides the minimum useful output; per-theme components
 * will overlay a styled map in later steps.
 */
export function LocationsBlock({ locations }: LocationsBlockProps) {
  if (!locations || locations.length === 0) return null

  // Group by day for legibility; unassigned (no day_number) go last.
  const byDay = new Map<number | null, LocationLike[]>()
  for (const loc of locations) {
    const key = typeof loc.day_number === 'number' ? loc.day_number : null
    const bucket = byDay.get(key) ?? []
    bucket.push(loc)
    byDay.set(key, bucket)
  }
  const dayKeys = Array.from(byDay.keys()).sort((a, b) => {
    if (a === null) return 1
    if (b === null) return -1
    return a - b
  })

  return (
    <section>
      <h2 className="text-2xl font-serif font-bold mb-6 text-theme-fg">Locations</h2>
      <ul className="space-y-3">
        {dayKeys.map((dayKey) => {
          const items = byDay.get(dayKey) ?? []
          return items.map((loc) => {
            const lat = numberOrNull(loc.latitude)
            const lng = numberOrNull(loc.longitude)
            const hasCoords = lat !== null && lng !== null
            const mapsUrl = hasCoords
              ? `https://www.google.com/maps/search/?api=1&query=${lat},${lng}`
              : null

            const dayLabel = dayKey === null ? null : `Day ${dayKey}`

            const inner = (
              <div className="flex items-start gap-3">
                <MapPin className="w-4 h-4 mt-0.5 flex-shrink-0 text-theme-accent" />
                <div className="flex-1 min-w-0">
                  <div className="flex items-baseline gap-2 flex-wrap">
                    <span className="text-theme-fg font-medium">{loc.name}</span>
                    {dayLabel && (
                      <span className="text-xs uppercase tracking-wider text-theme-fg-mute">
                        {dayLabel}
                      </span>
                    )}
                  </div>
                  {loc.notes && (
                    <p className="text-sm text-theme-fg-soft mt-0.5">{loc.notes}</p>
                  )}
                </div>
                {hasCoords && (
                  <span className="text-xs text-theme-accent whitespace-nowrap">
                    Open map ↗
                  </span>
                )}
              </div>
            )

            return (
              <li key={loc.id}>
                {mapsUrl ? (
                  <a
                    href={mapsUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="block p-3 border border-theme-rule rounded-lg hover:bg-theme-paper transition-colors"
                  >
                    {inner}
                  </a>
                ) : (
                  <div className="p-3 border border-theme-rule rounded-lg">{inner}</div>
                )}
              </li>
            )
          })
        })}
      </ul>
    </section>
  )
}
